sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: J+ayWGHJKcBW1XwqsoOxwyzkpfYUOcD0VmhyWs0fRHFzMP0X2cWFb9CoIcZDrZiZ+gwx3kMcG9oo2TiSOuhVhlR31HDBYwN1VpefTYrRGQoEtzkCMDC+XynOrAq1H42iRsisXMV7qLp+lOuMobZLSdCtPaWggTUQJVMS0KdLabZib805OP9i2O5MTMJFyTmr6aNxCQl/ELasIyUfDCoR/jswjYYVE2x7gAG3bFal3rP3stMDhLvDK29IzfNbZjbMjrTvQFIqNlQoyxJaU9Y199uVJgSZ0+R4EkADuDKhseOjbo4QLoJKsMX7v/Zmc//kwzj7QLhUPJIW0KYLkleNjcC5L+naN1qcMcuJsssc8s1Q6Q1CUZEV93AHXzd0ZQOyicvTRuoXOthYjldIgD/u89Ayjiq1pplGt1hcvILYxlT3b8fjCCovgPzGmCEqESvvLcLl99aCTMFRF/Jr6q9Vx3xS0djZLXXYqkRT9GZmTnaclCg2uLo5OoXhtUMjErfirs11nNxwgwYXmiXCPV/ogJxyaeaYfuZJMvtV7vzpOD/05/nt4had70T6jtDejA7CY7UnSVeZeGYGkdbcyV33UVRUWES+2cfaP3TfhyqrfmM6OjvpoksB9Myob4th6k3HEizzjNRvOHhsASjIkEhx+yknnlFE3SztFHBguBOpRmk=
  - secure: mf/ZZoVHRJlZlFU/Dbu+vj504/MXZpfrkO1+fPJ155iSiVCwp93dp/4DzCEr9tKdXDXQbGB3/GJYrFG2DvGlIlLhPSygeBtBaUvCWagU5MltfjPW2OINB+yJu9RNpdTwoL5yolwfmXMq50Ps13MCmwvvRC+3MMjMCTBUNJuTWk8/RioA/dW4WuDAHVsQ6nshobOBKYofANDmFfHa/F7Lj9nbhuFAnAe6AK20ZGIKuk+lt82rT+T4R68EyrhzMmZUI7gRoKGPOclJIDEPICbQit+ZRGLJF3TfJVxs2WvE0l4t7TtVWcbgL+7E3eFBGt4x2j4rY3mUecyHH28GZYssxfnFvmj1YftxEgQVcxuG1hWll9xNFTuW7Ncg1zsHHhJ+1qt08JfeND7L/q8OKF5u766Aa32U77xbOGbD58cqU4+xIdEwhsHXb9FEokx3J5j6toBioNiBbKs3hWYZ2Fvnx60Fo/kXr5VAJztBRpuZpRmToz2xoUzbcleEsk2ZT4SJYN6z1XXjja38DRa7r3L07YM0HzT4WrnoliOPIx1ZiebzXc3mEJCTEv6BSOu6fNefSUlcF7DcyKHbr0AWK4xHqohM9T9tf8f1Ch1WFvaK24sdpXUlnYrDotXMmko7dbPQkSf6l1rlJGhxBZoRYxBQNqBTkNqSOVFKuAVPn0uIztE=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - secure: HzVLXvfG1+bavNoOWfkcKi0mQA18IK2qBO+yYi7raALd52E0gejvi/aIQtRvStVRzd3yoMQTwz2/eUghS2TujZhWLBKNY6Se1udR+hp7ROD+RNZnJCPodBnqXB+k2Qa+O+XMHtvzpHkt8EaajCXzGtYmaPJb/3X5QdpSwk/khYKpzu6hFk8gpY1Me2F3QqD2E3NUmHbenMIiGqB1NbotizvGPWdDO6IKTJVSfgZq5mJ/15sLI0Y7NBsRXQt4Cag++D/k+zKuTfzDM6Lcs7XYDbTjwv3sSSYLNjN7ybKdvVswHXBUXNNKwCGM/wQ+7DzBoNxMYkewh49P0Y0biD4QKe4lOuTCjgY8NO6TymE3ccCj2eJRKFRVgoX2JE2wmYB7ASj4UetN4cXuqH3vP6kZppCXS72aysAwnpcviijAqm6v4dT8/aOw6I7lGACko0M8tiOMpCTmDl6v1rrFzxxOHDjQQlJIp9vO0DdU7fRqQae4lBvEKX7Zk4nqeU0qzAMbIhzjhnvRnVH/M0SarP7WyZU1SMMg/azv0AtJn8QrxolyghPdY+nLwnlGGjUyVhmAvVfOqanQnjnvFO07z+34J9HmlF6P/JyG/XfkWEFLollU13Lpb5qow+DjoXWcnCKqHfKlDYCgKfnwydvvgyv1muHpqayhXrXQPJb4xJjN110=
